language: generic
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod
            bionic main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
        packages:
        - powershell
before_install:
- sudo apt-get update
- sudo apt-get install python3.6-venv
install:
- sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
- ". ./scripts/init-env.sh"
- init-env
script:
- pwsh ./scripts/run.ps1
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file:
  - dist/FiraCodeScript-*.ttf
  skip_cleanup: true
  on:
    tags: true
  edge: true
env:
  global:
    secure: j/FVJ0N22rRhaBebx4WOGYiWcWqV+b63A+D7JolShm7kV+5S/5Xq/2CT6mp3bmk/kAWYUjgiIqwA2T/5Ycxzi8Z6jaNIP2UB1Uqh5lxXnnHHmK16XsKe1MkycnMFhsvOZ0K8solwZm4+qed5jCu0CALr1Ug6NSymhWpgZzloKxz9OzkgY1fC8EPLRfCNQCxc3Csdqy5CtS7yK91DhTImM+4OMLxGa21Diy7dkheBzmI2o6Akjhdr7LWAouYeRincFRV0MlYgrdxpSt6izKOPsmBxC9qCh3wavqwn6Ex4432+KotIrtnxowt4IuxvGBZfVoHZuIjPvGMm+XL+Uu7MtKjQl1+pm9eT7KbHbtFxzivUW1wYWHAL7DMfP3AvGqapPUxG27Q+Ew5i3L85PwTd5WXdqOnwPPFNgQW29Rp4lYzTd5+FU8Agja/oCWMyD/11uPCr1H6XIDHYq1FXw48LmhoXoSJ8vQn2pXWNXJIhfw7F52p0+8Vl8StRFQuTrt7kUErDv34CihyoKjJrOKTW+tFx0SV9vlkTjCy9TXAUGX6OaDqTilLkx47l+q1v6j2QzFd6RR9fw+dwF4qfJqay5tM4U84Er0OcS65rN5zm7ufkAiYnDO+VVtZ8eMpQlaQ8/xSO3GSoRDwZF0PCGMnZ6W7p8hf1zJpleUR/RRhOWTE=
