language: generic
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod
            bionic main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
        packages:
        - powershell
before_install:
- sudo apt-get update
- sudo apt-get install python3.6-venv
install:
- sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
- . ./scripts/init-env.sh
- init-env
script:
- pwsh ./scripts/run.ps1
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  user: ${GITHUB_USERNAME}
  password: ${GITHUB_PASSWORD}
  file:
  - "./dist/FiraCodeScript-Regular.ttf"
  - "./dist/FiraCodeScript-Italic.ttf"
  - "./dist/FiraCodeScript-Bold.ttf"
  skip_cleanup: true
  on:
    tags: true
  edge: true
