language: generic
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod
            bionic main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
        packages:
        - powershell
before_install:
- sudo apt-get update
- sudo apt-get install python3.6-venv
install:
- sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
- "./scripts/init-env.sh"
script:
- pwsh ./scripts/run.ps1
env:
  global:
    secure: nw5hq1bFTqBFV2TcyekwYiyVxxnBjEEpURSIbHYu9qukMbPlb4FfsdIHRCmK5HU9iCiUQtREzB+Je1Oas2rZ+9NIsru+ilzp4otkcvmeX4Rtr8PeAzui5iYEQ1nfYm3haz1315ZIq8IP03eJ68u7xVX1q+ZoaSm+0lA7d4CF+wW6ssrRmu3f1BVCF0rcQ4vwlp+GVHB4+jHCaddTRwQAKFTjCrgOde2m77/sdIsZz3DMOfg3Yx1Wf520/ayRRiDd/TylOSz3vcNECU5jzAv2hyHQzbeiET11EqGKGXRHV1GM5WLxvpBUkb1uKz6VtdU3c6Qe7N5NvZ6DJmO8i3NVcb0hdg6+r+oHml1GhdsnfQ0g6qTmQ1yXzxkuxhaBzO14/qcJVeYD+hzXhzi1cTy7zuPnrkQTxdQjTmVjGclNncsqZvWDhyZXps1b1fdGe0Tvd6rQKTvBJ9Q/oWgEW9YQY5Aqxz+IAslZ/8jwjVDomLTQUmGYVXpKl3S7u+NXwR/W7OVaMjmSHTlAR2FWWd0eZ0BeqyJJ4UuLCJOg81Jr/EbTZyonMXmVYhT33crp78OYZibmAAGG0gT4TGxiMD0nn8Icqyb7/wghM+IkekJtjPfejvyyohp4xMYEELNbirE4woNXTYbuJR4VCaaDFJHefWC9rKrqq0aklTjED+eYlak=
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - dist/FiraCodeScript-*.ttf
  skip_cleanup: true
  on:
    tags: true
  edge: true
