language: generic
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod
            bionic main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
        packages:
        - powershell
before_install:
- sudo apt-get update
- sudo apt-get install python3.6-venv
install:
- sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
- "./scripts/init-env.sh"
script:
- pwsh ./scripts/run.ps1
deploy:
  provider: releases
  file_glob: true
  file:
  - dist/FiraCodeScript-*.ttf
  skip_cleanup: true
  on:
    tags: true
  edge: true
env:
  global:
    secure: p7uWWftXbx6VGxYdaSLHPAJGwM8NcSmRbGJ+7Vm/i51UIB5vuJi04nRpjctA85tNAEWBpHotDW9fWlxs+Sp4spFlrCCOIzIdikKODDUqQKPVqw1hd1Vn7P3Y//YuEL2jkFqyUTT5CNLm6dMgSuoQ7c5iszyrbzXGtMFUV6vsejUYD0/RDO2+TwLNCozE7DbhODBilnT44wA9xwIp/kHSXcmWVV0B2m3E8EqBWYJF4AIMRHn3sIp+AT02Si55zLdKef3m51vfOHPa1tfP6tsR8XUaK1PEbIdunlAIAskoVk2cqk41cOeDhh5XWxh9LXnQoKQoP87gdb53j6VmdFWb4sVsdnzkl0hV/s8QknkvxC88exjFh/FxtZ9X1dSQwilb80EN4AjAEVmPd1dWrE7i23p6MckQwhS/d0xZjf4JuPWmsW4U/Ocg2bhILNggWjgu4XmTst8wDgkpQQzghKkyBIH+C9hX2GD4gtD0XsitH5U5VhJd8cgJdLGvS2oDk3nGTfdTLpfRJGJqfa0+1llaYTdyIjQSL+9k9NXzUJIGs3uULYzdAfGyOTIlF/Uqsh586OK80713HSXgw8VnaTh7qd0hXRBjyfHeMQCQskHZe8LR3I5iAL3qq3yTQIvQaAO16oA1viLT0QH+hbKQGQbm3EsaZafVhmwyl2ymlwBRPRc=
