language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
install:
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
  - sudo apt update
  - sudo apt install python3-venv
  - . ./scripts/init-env.sh
  - init-env
# command to run tests
script:
  - pwsh ./scripts/run.sh